In [2]:
# rank genes for biased mask training
from fine_tune_bioaid import *

In [5]:
data, _, _ = load_data("../UCLThesis/data/BIOAID_unlabelled_tpm_PC0.001_log2.parquet", return_df=True)
data

                 ENSG00000000003  ...  ENSG00000290149
BIOAIDUR7635328        -3.596095  ...        -9.965784
BIOAIDUR7635329        -5.949696  ...        -9.965784
BIOAIDUR7635330        -4.505073  ...        -9.965784
BIOAIDUR7635331        -2.106934  ...        -9.965784
BIOAIDUR7635333        -4.988783  ...        -9.965784
...                          ...  ...              ...
X962                   -0.354760  ...        -0.695499
X966                   -0.335936  ...        -9.965784
X986                   -0.806617  ...        -9.965784
X990                   -0.994432  ...        -3.349606
X994                   -0.513880  ...         0.315928

[1251 rows x 20010 columns]

In [15]:
bulkformer_gene_list = set(pd.read_csv("~/UCLThesis/data/bulkformer_gene_info.csv")["ensg_id"])
len(bulkformer_gene_list)

20010

In [6]:
labelled_df = pd.read_parquet("~/UCLThesis/data/BIOAID_UCL_Oxford_361_labelled.parquet")
labelled_df

          cohort  age  ... ENSG00000291316 ENSG00000291317
UP2975       UCL   74  ...        0.596682        1.612867
UP2978       UCL   20  ...       -1.048019        1.763795
UP2990       UCL   30  ...       -9.965784        2.047272
UP3020       UCL   88  ...       -1.238767        0.879367
UP3026       UCL   83  ...       -9.965784        1.518576
...          ...  ...  ...             ...             ...
OX.10210  Oxford   83  ...        1.958946        0.824596
OX.10245  Oxford   65  ...       -4.283669        0.582776
OX.10318  Oxford   83  ...       -0.004720        1.872290
OX.10393  Oxford   60  ...        1.367773        0.189153
OX.10293  Oxford   35  ...        2.357107        1.061359

[361 rows x 40605 columns]

In [46]:
# Binary infection label: 1 for Viral or Bacterial & Viral, else 0
labelled_df['infection_status'] = labelled_df['micro_diagnosis'].isin(['Viral', 'Bacterial & Viral']).astype(int)

# Gene columns
gene_cols = [col for col in labelled_df.columns if col.startswith('ENSG') and col in bulkformer_gene_list]

# Efficiently replace log2(0.001) ≈ -9.965784 with -10 as mask token
labelled_df[gene_cols] = np.where(
    np.isclose(labelled_df[gene_cols].values, -9.965784, atol=0.2),
    -10,
    labelled_df[gene_cols].values
)

# Compute per-class Z-scores while treating -10 as NaN
ranked_genes = {}
for status in [0, 1]:
    subset = labelled_df[labelled_df['infection_status'] == status][gene_cols]
    masked = subset.replace(-10, np.nan)
    means = masked.mean()
    # stds = masked.std()
    
    # Remove small stds that blow up z-scores
    # valid_counts = masked.notna().sum()
    # stds[valid_counts < 20] = np.nan

    # z_scores = means / stds
    z_scores = means
    # Check for near-zero std
    # print("Genes with very small stds in class", status)
    # display(stds[stds < 1e-2].sort_values())  # REMOVE LATER
    ranked_genes[f'class_{status}'] = z_scores

# Compute and rank Z-score differences (class 1 - class 0)
zscore_diff = ranked_genes['class_1'] - ranked_genes['class_0']
zscore_diff = zscore_diff.sort_values(ascending=False)
zscore_diff

ENSG00000184108    7.076230
ENSG00000166603    6.622736
ENSG00000164488    6.429877
ENSG00000187170    6.146248
ENSG00000206422    5.593785
                     ...
ENSG00000289760         NaN
ENSG00000289761         NaN
ENSG00000289764         NaN
ENSG00000289766         NaN
ENSG00000289767         NaN
Length: 20010, dtype: float64

In [50]:
MASK_PROB = 0.15
top_genes = int(MASK_PROB * 20010)
# just use 3000 honestly?
zscore_diff.index[:top_genes].to_series().to_csv("data/top_mean_diff_genes.csv", index=False)

In [57]:
diffs = pd.read_csv("data/top_mean_diff_genes.csv")
set(diffs.iloc[:, 0])

{'ENSG00000244509',
 'ENSG00000064195',
 'ENSG00000130707',
 'ENSG00000106366',
 'ENSG00000230054',
 'ENSG00000188313',
 'ENSG00000163512',
 'ENSG00000179695',
 'ENSG00000274049',
 'ENSG00000275163',
 'ENSG00000250374',
 'ENSG00000103855',
 'ENSG00000128965',
 'ENSG00000198794',
 'ENSG00000176092',
 'ENSG00000104818',
 'ENSG00000117475',
 'ENSG00000162542',
 'ENSG00000171320',
 'ENSG00000196990',
 'ENSG00000133104',
 'ENSG00000103353',
 'ENSG00000112137',
 'ENSG00000002549',
 'ENSG00000283988',
 'ENSG00000145945',
 'ENSG00000151725',
 'ENSG00000159450',
 'ENSG00000171067',
 'ENSG00000162643',
 'ENSG00000041880',
 'ENSG00000122756',
 'ENSG00000142731',
 'ENSG00000043591',
 'ENSG00000172037',
 'ENSG00000269095',
 'ENSG00000149428',
 'ENSG00000164532',
 'ENSG00000100097',
 'ENSG00000264668',
 'ENSG00000181333',
 'ENSG00000100604',
 'ENSG00000163395',
 'ENSG00000174307',
 'ENSG00000160293',
 'ENSG00000112118',
 'ENSG00000137558',
 'ENSG00000028116',
 'ENSG00000176909',
 'ENSG00000164932',
 'ENSG00000169789',
 'ENSG00000274944',
 'ENSG00000170777',
 'ENSG00000198929',
 'ENSG00000182492',
 'ENSG00000007350',
 'ENSG00000281593',
 'ENSG00000185745',
 'ENSG00000187510',
 'ENSG00000043143',
 'ENSG00000142961',
 'ENSG00000134057',
 'ENSG00000082516',
 'ENSG00000173801',
 'ENSG00000184867',
 'ENSG00000150361',
 'ENSG00000160716',
 'ENSG00000144354',
 'ENSG00000258461',
 'ENSG00000131941',
 'ENSG00000085449',
 'ENSG00000160469',
 'ENSG00000198547',
 'ENSG00000107816',
 'ENSG00000138698',
 'ENSG00000115085',
 'ENSG00000164051',
 'ENSG00000124920',
 'ENSG00000115109',
 'ENSG00000149021',
 'ENSG00000109534',
 'ENSG00000145808',
 'ENSG00000111049',
 'ENSG00000170270',
 'ENSG00000278599',
 'ENSG00000172350',
 'ENSG00000011426',
 'ENSG00000146232',
 'ENSG00000117143',
 'ENSG00000110497',
 'ENSG00000172421',
 'ENSG00000177283',
 'ENSG00000137200',
 'ENSG00000143382',
 'ENSG00000285085',
 'ENSG00000087076',
 'ENSG00000158773',
 'ENSG00000188643',
 'ENSG00000185133',
 'ENSG00000204671',
 'ENSG00000285471',
 'ENSG00000165496',
 'ENSG00000172183',
 'ENSG00000134539',
 'ENSG00000172009',
 'ENSG00000149403',
 'ENSG00000107864',
 'ENSG00000172023',
 'ENSG00000114993',
 'ENSG00000213402',
 'ENSG00000174600',
 'ENSG00000135443',
 'ENSG00000072121',
 'ENSG00000006788',
 'ENSG00000198914',
 'ENSG00000185340',
 'ENSG00000104951',
 'ENSG00000205899',
 'ENSG00000023191',
 'ENSG00000112110',
 'ENSG00000133216',
 'ENSG00000254692',
 'ENSG00000137364',
 'ENSG00000011052',
 'ENSG00000169129',
 'ENSG00000120280',
 'ENSG00000169397',
 'ENSG00000225110',
 'ENSG00000100253',
 'ENSG00000099822',
 'ENSG00000107731',
 'ENSG00000117632',
 'ENSG00000145734',
 'ENSG00000178685',
 'ENSG00000162344',
 'ENSG00000229579',
 'ENSG00000174963',
 'ENSG00000134940',
 'ENSG00000275379',
 'ENSG00000141314',
 'ENSG00000167085',
 'ENSG00000111907',
 'ENSG00000126218',
 'ENSG00000138316',
 'ENSG00000166598',
 'ENSG00000185482',
 'ENSG00000109805',
 'ENSG00000255855',
 'ENSG00000136213',
 'ENSG00000152558',
 'ENSG00000179218',
 'ENSG00000101435',
 'ENSG00000277856',
 'ENSG00000160233',
 'ENSG00000185758',
 'ENSG00000139292',
 'ENSG00000112576',
 'ENSG00000170373',
 'ENSG00000105370',
 'ENSG00000143257',
 'ENSG00000187944',
 'ENSG00000259529',
 'ENSG00000187094',
 'ENSG00000275183',
 'ENSG00000198911',
 'ENSG00000142039',
 'ENSG00000167157',
 'ENSG00000016082',
 'ENSG00000151240',
 'ENSG00000269720',
 'ENSG00000243811',
 'ENSG00000203760',
 'ENSG00000154277',
 'ENSG00000168268',
 'ENSG00000139219',
 'ENSG00000164053',
 'ENSG00000138035',
 'ENSG00000196358',
 'ENSG00000105974',
 'ENSG00000247626',
 'ENSG00000079691',
 'ENSG00000181004',
 'ENSG00000146192',
 'ENSG00000171722',
 'ENSG00000112562',
 'ENSG00000109943',
 'ENSG00000107562',
 'ENSG00000085741',
 'ENSG00000137726',
 'ENSG00000149554',
 'ENSG00000250821',
 'ENSG00000163285',
 'ENSG00000068781',
 'ENSG00000187815',
 'ENSG00000167646',
 'ENSG00000167123',
 'ENSG00000124302',
 'ENSG00000183559',
 'ENSG00000274226',
 'ENSG00000163202',
 'ENSG00000138135',
 'ENSG00000175602',
 'ENSG00000243414',
 'ENSG00000180061',
 'ENSG00000137411',
 'ENSG00000109738',
 'ENSG00000263353',
 'ENSG00000230594',
 'ENSG00000122068',
 'ENSG00000153347',
 'ENSG00000233822',
 'ENSG00000235162',
 'ENSG00000181218',
 'ENSG00000256825',
 'ENSG00000074695',
 'ENSG00000125844',
 'ENSG00000160318',
 'ENSG00000179111',
 'ENSG00000071462',
 'ENSG00000188488',
 'ENSG00000176890',
 'ENSG00000163661',
 'ENSG00000055130',
 'ENSG00000166166',
 'ENSG00000254673',
 'ENSG00000166164',
 'ENSG00000113070',
 'ENSG00000177150',
 'ENSG00000196684',
 'ENSG00000244255',
 'ENSG00000254229',
 'ENSG00000115353',
 'ENSG00000179630',
 'ENSG00000187045',
 'ENSG00000168263',
 'ENSG00000172403',
 'ENSG00000166106',
 'ENSG00000157111',
 'ENSG00000196576',
 'ENSG00000257008',
 'ENSG00000214872',
 'ENSG00000268173',
 'ENSG00000196748',
 'ENSG00000204099',
 'ENSG00000163064',
 'ENSG00000181963',
 'ENSG00000099901',
 'ENSG00000151470',
 'ENSG00000170581',
 'ENSG00000254979',
 'ENSG00000100889',
 'ENSG00000198901',
 'ENSG00000115593',
 'ENSG00000254986',
 'ENSG00000196497',
 'ENSG00000166862',
 'ENSG00000161640',
 'ENSG00000260729',
 'ENSG00000213424',
 'ENSG00000182601',
 'ENSG00000258653',
 'ENSG00000175197',
 'ENSG00000108091',
 'ENSG00000117984',
 'ENSG00000100605',
 'ENSG00000117834',
 'ENSG00000166595',
 'ENSG00000106789',
 'ENSG00000167842',
 'ENSG00000258806',
 'ENSG00000163815',
 'ENSG00000273238',
 'ENSG00000197110',
 'ENSG00000102287',
 'ENSG00000182747',
 'ENSG00000239713',
 'ENSG00000109321',
 'ENSG00000197471',
 'ENSG00000126458',
 'ENSG00000073350',
 'ENSG00000066405',
 'ENSG00000268916',
 'ENSG00000160753',
 'ENSG00000126460',
 'ENSG00000113212',
 'ENSG00000186788',
 'ENSG00000198719',
 'ENSG00000166450',
 'ENSG00000184384',
 'ENSG00000158292',
 'ENSG00000162753',
 'ENSG00000162614',
 'ENSG00000288626',
 'ENSG00000089225',
 'ENSG00000204397',
 'ENSG00000165895',
 'ENSG00000108984',
 'ENSG00000214102',
 'ENSG00000174482',
 'ENSG00000146674',
 'ENSG00000110092',
 'ENSG00000259112',
 'ENSG00000180205',
 'ENSG00000196406',
 'ENSG00000267426',
 'ENSG00000147443',
 'ENSG00000144191',
 'ENSG00000111912',
 'ENSG00000176105',
 'ENSG00000115155',
 'ENSG00000137449',
 'ENSG00000115415',
 'ENSG00000181085',
 'ENSG00000130589',
 'ENSG00000144035',
 'ENSG00000065060',
 'ENSG00000227057',
 'ENSG00000139410',
 'ENSG00000215217',
 'ENSG00000160072',
 'ENSG00000177103',
 'ENSG00000110944',
 'ENSG00000126467',
 'ENSG00000275572',
 'ENSG00000138688',
 'ENSG00000166689',
 'ENSG00000163734',
 'ENSG00000139269',
 'ENSG00000180219',
 'ENSG00000072571',
 'ENSG00000109971',
 'ENSG00000197837',
 'ENSG00000129673',
 'ENSG00000236637',
 'ENSG00000162383',
 'ENSG00000131037',
 'ENSG00000118707',
 'ENSG00000274290',
 'ENSG00000184897',
 'ENSG00000102243',
 'ENSG00000268083',
 'ENSG00000206127',
 'ENSG00000121858',
 'ENSG00000142619',
 'ENSG00000288614',
 'ENSG00000066651',
 'ENSG00000117448',
 'ENSG00000249751',
 'ENSG00000115138',
 'ENSG00000134318',
 'ENSG00000085365',
 'ENSG00000284283',
 'ENSG00000123131',
 'ENSG00000149577',
 'ENSG00000102055',
 'ENSG00000204065',
 'ENSG00000143228',
 'ENSG00000129538',
 'ENSG00000140067',
 'ENSG00000203909',
 'ENSG00000188322',
 'ENSG00000141664',
 'ENSG00000189266',
 'ENSG00000126262',
 'ENSG00000165806',
 'ENSG00000130520',
 'ENSG00000135801',
 'ENSG00000089685',
 'ENSG00000120549',
 'ENSG00000166793',
 'ENSG00000136883',
 'ENSG00000124299',
 'ENSG00000148602',
 'ENSG00000168496',
 'ENSG00000176884',
 'ENSG00000157657',
 'ENSG00000172465',
 'ENSG00000163145',
 'ENSG00000179331',
 'ENSG00000100678',
 'ENSG00000155093',
 'ENSG00000072858',
 'ENSG00000147799',
 'ENSG00000197745',
 'ENSG00000124762',
 'ENSG00000165730',
 'ENSG00000149929',
 'ENSG00000127780',
 'ENSG00000143333',
 'ENSG00000129757',
 'ENSG00000272636',
 'ENSG00000164054',
 'ENSG00000265972',
 'ENSG00000042493',
 'ENSG00000183114',
 'ENSG00000196218',
 'ENSG00000162755',
 'ENSG00000106392',
 'ENSG00000096433',
 'ENSG00000137414',
 'ENSG00000106591',
 'ENSG00000185551',
 'ENSG00000204516',
 'ENSG00000221840',
 'ENSG00000101098',
 'ENSG00000169783',
 'ENSG00000155754',
 'ENSG00000102076',
 'ENSG00000255432',
 'ENSG00000179593',
 'ENSG00000196369',
 'ENSG00000254415',
 'ENSG00000171877',
 'ENSG00000155660',
 'ENSG00000203786',
 'ENSG00000261652',
 'ENSG00000262179',
 'ENSG00000182583',
 'ENSG00000187806',
 'ENSG00000263761',
 'ENSG00000102804',
 'ENSG00000119640',
 'ENSG00000160867',
 'ENSG00000183878',
 'ENSG00000171848',
 'ENSG00000172935',
 'ENSG00000103742',
 'ENSG00000059573',
 'ENSG00000130816',
 'ENSG00000105173',
 'ENSG00000111911',
 'ENSG00000116521',
 'ENSG00000164105',
 'ENSG00000170873',
 'ENSG00000129810',
 'ENSG00000285171',
 'ENSG00000164283',
 'ENSG00000102802',
 'ENSG00000204060',
 'ENSG00000160563',
 'ENSG00000185467',
 'ENSG00000139329',
 'ENSG00000100373',
 'ENSG00000198286',
 'ENSG00000181240',
 'ENSG00000106772',
 'ENSG00000181381',
 'ENSG00000081014',
 'ENSG00000171611',
 'ENSG00000143344',
 'ENSG00000005981',
 'ENSG00000169047',
 'ENSG00000276747',
 'ENSG00000164611',
 'ENSG00000114547',
 'ENSG00000176540',
 'ENSG00000155495',
 'ENSG00000021852',
 'ENSG00000164483',
 'ENSG00000126970',
 'ENSG00000168298',
 'ENSG00000283428',
 'ENSG00000115339',
 'ENSG00000147432',
 'ENSG00000198821',
 'ENSG00000142684',
 'ENSG00000162975',
 'ENSG00000196778',
 'ENSG00000128203',
 'ENSG00000116819',
 'ENSG00000136717',
 'ENSG00000168243',
 'ENSG00000173040',
 'ENSG00000164647',
 'ENSG00000080573',
 'ENSG00000160767',
 'ENSG00000144452',
 'ENSG00000161800',
 'ENSG00000174339',
 'ENSG00000198829',
 'ENSG00000127564',
 'ENSG00000198691',
 'ENSG00000075234',
 'ENSG00000146678',
 'ENSG00000166845',
 'ENSG00000258588',
 'ENSG00000100596',
 'ENSG00000198211',
 'ENSG00000163508',
 'ENSG00000108759',
 'ENSG00000198440',
 'ENSG00000206422',
 'ENSG00000103710',
 'ENSG00000126733',
 'ENSG00000123992',
 'ENSG00000138670',
 'ENSG00000169862',
 'ENSG00000154127',
 'ENSG00000183269',
 'ENSG00000130511',
 'ENSG00000269590',
 'ENSG00000240764',
 'ENSG00000188991',
 'ENSG00000167601',
 'ENSG00000153157',
 'ENSG00000146670',
 'ENSG00000070047',
 'ENSG00000101057',
 'ENSG00000140750',
 'ENSG00000092377',
 'ENSG00000179021',
 'ENSG00000103174',
 'ENSG00000087128',
 'ENSG00000177938',
 'ENSG00000124635',
 'ENSG00000137135',
 'ENSG00000269502',
 'ENSG00000172348',
 'ENSG00000274641',
 'ENSG00000120217',
 'ENSG00000188811',
 'ENSG00000142675',
 'ENSG00000203877',
 'ENSG00000119705',
 'ENSG00000135148',
 'ENSG00000106617',
 'ENSG00000214814',
 'ENSG00000047662',
 'ENSG00000235780',
 'ENSG00000099399',
 'ENSG00000167207',
 'ENSG00000112852',
 'ENSG00000284438',
 'ENSG00000159674',
 'ENSG00000089847',
 'ENSG00000072201',
 'ENSG00000152749',
 'ENSG00000157470',
 'ENSG00000255425',
 'ENSG00000130413',
 'ENSG00000254402',
 'ENSG00000130595',
 'ENSG00000172322',
 'ENSG00000164485',
 'ENSG00000259384',
 'ENSG00000181634',
 'ENSG00000243501',
 'ENSG00000232264',
 'ENSG00000105726',
 'ENSG00000257921',
 'ENSG00000166289',
 'ENSG00000184675',
 'ENSG00000213614',
 'ENSG00000089127',
 'ENSG00000110848',
 'ENSG00000184227',
 'ENSG00000186787',
 'ENSG00000261832',
 'ENSG00000213689',
 'ENSG00000119421',
 'ENSG00000185880',
 'ENSG00000134201',
 'ENSG00000169570',
 'ENSG00000016602',
 'ENSG00000074211',
 'ENSG00000177854',
 'ENSG00000093072',
 'ENSG00000164825',
 'ENSG00000155313',
 'ENSG00000175664',
 'ENSG00000171860',
 'ENSG00000197372',
 'ENSG00000145990',
 'ENSG00000163515',
 'ENSG00000100450',
 'ENSG00000110108',
 'ENSG00000133119',
 'ENSG00000049449',
 'ENSG00000100665',
 'ENSG00000131781',
 'ENSG00000090520',
 'ENSG00000177707',
 'ENSG00000125657',
 'ENSG00000273520',
 'ENSG00000142449',
 'ENSG00000096088',
 'ENSG00000182054',
 'ENSG00000285133',
 'ENSG00000136689',
 'ENSG00000115221',
 'ENSG00000166262',
 'ENSG00000170312',
 'ENSG00000231389',
 'ENSG00000106100',
 'ENSG00000171916',
 'ENSG00000177675',
 'ENSG00000143498',
 'ENSG00000180938',
 'ENSG00000001617',
 'ENSG00000180900',
 'ENSG00000174599',
 'ENSG00000171843',
 'ENSG00000006611',
 'ENSG00000266728',
 'ENSG00000188580',
 'ENSG00000145087',
 'ENSG00000254706',
 'ENSG00000266074',
 'ENSG00000119383',
 'ENSG00000228672',
 'ENSG00000273213',
 'ENSG00000078098',
 'ENSG00000169583',
 'ENSG00000221957',
 'ENSG00000124201',
 'ENSG00000069696',
 'ENSG00000092607',
 'ENSG00000102048',
 'ENSG00000187918',
 'ENSG00000151365',
 'ENSG00000110057',
 'ENSG00000105402',
 'ENSG00000158373',
 'ENSG00000155366',
 'ENSG00000138385',
 'ENSG00000288859',
 'ENSG00000125903',
 'ENSG00000170948',
 'ENSG00000111405',
 'ENSG00000214194',
 'ENSG00000176435',
 'ENSG00000176029',
 'ENSG00000169908',
 'ENSG00000069018',
 'ENSG00000187773',
 'ENSG00000100263',
 'ENSG00000143367',
 'ENSG00000163564',
 'ENSG00000140105',
 'ENSG00000174016',
 'ENSG00000275520',
 'ENSG00000283071',
 'ENSG00000103335',
 'ENSG00000289549',
 'ENSG00000183971',
 'ENSG00000148935',
 'ENSG00000204227',
 'ENSG00000147036',
 'ENSG00000088836',
 'ENSG00000183527',
 'ENSG00000166562',
 'ENSG00000266953',
 'ENSG00000010030',
 'ENSG00000094804',
 'ENSG00000290147',
 'ENSG00000172538',
 'ENSG00000085998',
 'ENSG00000185722',
 'ENSG00000105251',
 'ENSG00000284691',
 'ENSG00000197766',
 'ENSG00000139438',
 'ENSG00000175048',
 'ENSG00000172123',
 'ENSG00000248235',
 'ENSG00000174358',
 'ENSG00000137807',
 'ENSG00000283228',
 'ENSG00000131477',
 'ENSG00000203852',
 'ENSG00000115750',
 'ENSG00000101342',
 'ENSG00000234127',
 'ENSG00000187908',
 'ENSG00000166387',
 'ENSG00000101255',
 'ENSG00000134020',
 'ENSG00000111602',
 'ENSG00000166049',
 'ENSG00000158113',
 'ENSG00000147081',
 'ENSG00000138207',
 'ENSG00000270276',
 'ENSG00000164308',
 'ENSG00000198848',
 'ENSG00000168961',
 'ENSG00000136824',
 'ENSG00000278637',
 'ENSG00000111186',
 'ENSG00000102935',
 'ENSG00000184160',
 'ENSG00000129173',
 'ENSG00000161692',
 'ENSG00000142686',
 'ENSG00000168077',
 'ENSG00000155760',
 'ENSG00000105464',
 'ENSG00000114745',
 'ENSG00000135899',
 'ENSG00000100342',
 'ENSG00000041353',
 'ENSG00000127884',
 'ENSG00000138614',
 'ENSG00000101412',
 'ENSG00000164465',
 'ENSG00000138496',
 'ENSG00000168016',
 'ENSG00000105287',
 'ENSG00000112149',
 'ENSG00000173786',
 'ENSG00000188610',
 'ENSG00000232434',
 'ENSG00000137168',
 'ENSG00000140464',
 'ENSG00000215343',
 'ENSG00000181588',
 'ENSG00000099889',
 'ENSG00000182636',
 'ENSG00000126882',
 'ENSG00000122643',
 'ENSG00000085999',
 'ENSG00000110900',
 'ENSG00000205884',
 'ENSG00000173302',
 'ENSG00000128654',
 'ENSG00000198092',
 'ENSG00000232258',
 'ENSG00000128228',
 'ENSG00000108039',
 'ENSG00000256870',
 'ENSG00000226600',
 'ENSG00000066735',
 'ENSG00000186479',
 'ENSG00000165029',
 'ENSG00000147650',
 'ENSG00000166603',
 'ENSG00000138646',
 'ENSG00000164309',
 'ENSG00000142089',
 'ENSG00000176219',
 'ENSG00000069482',
 'ENSG00000162616',
 'ENSG00000254413',
 'ENSG00000239887',
 'ENSG00000165832',
 'ENSG00000066185',
 'ENSG00000052795',
 'ENSG00000160888',
 'ENSG00000183770',
 'ENSG00000168539',
 'ENSG00000174137',
 'ENSG00000135211',
 'ENSG00000273983',
 'ENSG00000226929',
 'ENSG00000142227',
 'ENSG00000169258',
 'ENSG00000147202',
 'ENSG00000205730',
 'ENSG00000115380',
 'ENSG00000140284',
 'ENSG00000085733',
 'ENSG00000116785',
 'ENSG00000178999',
 'ENSG00000115295',
 'ENSG00000117148',
 'ENSG00000162998',
 'ENSG00000154415',
 'ENSG00000114771',
 'ENSG00000185697',
 'ENSG00000250741',
 'ENSG00000237289',
 'ENSG00000169385',
 'ENSG00000164334',
 'ENSG00000113657',
 'ENSG00000168542',
 'ENSG00000274252',
 'ENSG00000240505',
 'ENSG00000101596',
 'ENSG00000213921',
 'ENSG00000261272',
 'ENSG00000261739',
 'ENSG00000174032',
 'ENSG00000100949',
 'ENSG00000132646',
 'ENSG00000185272',
 'ENSG00000197381',
 'ENSG00000149131',
 'ENSG00000181195',
 'ENSG00000169247',
 'ENSG00000198088',
 'ENSG00000229474',
 'ENSG00000119922',
 'ENSG00000093009',
 'ENSG00000171943',
 'ENSG00000184345',
 'ENSG00000176919',
 'ENSG00000171729',
 'ENSG00000250641',
 'ENSG00000139880',
 'ENSG00000204392',
 'ENSG00000135454',
 'ENSG00000197705',
 'ENSG00000118523',
 'ENSG00000288534',
 'ENSG00000231051',
 'ENSG00000145850',
 'ENSG00000109511',
 'ENSG00000101298',
 'ENSG00000054690',
 'ENSG00000157456',
 'ENSG00000070159',
 'ENSG00000173068',
 'ENSG00000114450',
 'ENSG00000183978',
 'ENSG00000157087',
 'ENSG00000154719',
 'ENSG00000256660',
 'ENSG00000146918',
 'ENSG00000116745',
 'ENSG00000144852',
 'ENSG00000172432',
 'ENSG00000107949',
 'ENSG00000189430',
 'ENSG00000185897',
 'ENSG00000284491',
 'ENSG00000175643',
 'ENSG00000139515',
 'ENSG00000146809',
 'ENSG00000167371',
 'ENSG00000105939',
 'ENSG00000112343',
 'ENSG00000162654',
 'ENSG00000161929',
 'ENSG00000075043',
 'ENSG00000153093',
 'ENSG00000141736',
 'ENSG00000181109',
 'ENSG00000112319',
 'ENSG00000285043',
 'ENSG00000125826',
 'ENSG00000164488',
 'ENSG00000170175',
 'ENSG00000275714',
 'ENSG00000278588',
 'ENSG00000108702',
 'ENSG00000185608',
 'ENSG00000272921',
 'ENSG00000185303',
 'ENSG00000145794',
 'ENSG00000048028',
 'ENSG00000104044',
 'ENSG00000186038',
 'ENSG00000205097',
 'ENSG00000166091',
 'ENSG00000154118',
 'ENSG00000183010',
 'ENSG00000159189',
 'ENSG00000175520',
 'ENSG00000113504',
 'ENSG00000145029',
 'ENSG00000132613',
 'ENSG00000118156',
 'ENSG00000186185',
 'ENSG00000065328',
 'ENSG00000091482',
 'ENSG00000159788',
 'ENSG00000054148',
 'ENSG00000177047',
 'ENSG00000133328',
 'ENSG00000102081',
 'ENSG00000196873',
 'ENSG00000133740',
 'ENSG00000132881',
 'ENSG00000168913',
 'ENSG00000204501',
 'ENSG00000157985',
 'ENSG00000198108',
 'ENSG00000106785',
 'ENSG00000178175',
 'ENSG00000178662',
 'ENSG00000152492',
 'ENSG00000156469',
 'ENSG00000259803',
 'ENSG00000157593',
 'ENSG00000177045',
 'ENSG00000221926',
 'ENSG00000127743',
 'ENSG00000184350',
 'ENSG00000128335',
 'ENSG00000164093',
 'ENSG00000198842',
 'ENSG00000117226',
 'ENSG00000255641',
 'ENSG00000104972',
 'ENSG00000177873',
 'ENSG00000120690',
 'ENSG00000198574',
 'ENSG00000204335',
 'ENSG00000013573',
 'ENSG00000189280',
 'ENSG00000074410',
 'ENSG00000137869',
 'ENSG00000123610',
 'ENSG00000103249',
 'ENSG00000169903',
 'ENSG00000154654',
 'ENSG00000183828',
 'ENSG00000121851',
 'ENSG00000135114',
 'ENSG00000159398',
 'ENSG00000175229',
 'ENSG00000187475',
 'ENSG00000152689',
 'ENSG00000073861',
 'ENSG00000163644',
 'ENSG00000178372',
 'ENSG00000196839',
 'ENSG00000112419',
 'ENSG00000135900',
 'ENSG00000162852',
 'ENSG00000196422',
 'ENSG00000275832',
 'ENSG00000081985',
 'ENSG00000120054',
 'ENSG00000114638',
 'ENSG00000198889',
 'ENSG00000180228',
 'ENSG00000146005',
 'ENSG00000181649',
 'ENSG00000184292',
 'ENSG00000136147',
 'ENSG00000120539',
 'ENSG00000030582',
 'ENSG00000167131',
 'ENSG00000155636',
 'ENSG00000157303',
 'ENSG00000117228',
 'ENSG00000237110',
 'ENSG00000240065',
 'ENSG00000067842',
 'ENSG00000132693',
 'ENSG00000168811',
 'ENSG00000135093',
 'ENSG00000205186',
 'ENSG00000136104',
 'ENSG00000163872',
 'ENSG00000138778',
 'ENSG00000110079',
 'ENSG00000111247',
 'ENSG00000197122',
 'ENSG00000183486',
 'ENSG00000214013',
 'ENSG00000137502',
 'ENSG00000108961',
 'ENSG00000142549',
 'ENSG00000126878',
 'ENSG00000146858',
 'ENSG00000122729',
 'ENSG00000206043',
 'ENSG00000184967',
 'ENSG00000128284',
 'ENSG00000215853',
 'ENSG00000151364',
 'ENSG00000132669',
 'ENSG00000135069',
 'ENSG00000268902',
 'ENSG00000177485',
 'ENSG00000241119',
 'ENSG00000187942',
 'ENSG00000101188',
 'ENSG00000263639',
 'ENSG00000116133',
 'ENSG00000276070',
 'ENSG00000162849',
 'ENSG00000175592',
 'ENSG00000164294',
 'ENSG00000080986',
 'ENSG00000162512',
 'ENSG00000157601',
 'ENSG00000214042',
 'ENSG00000071575',
 'ENSG00000278463',
 'ENSG00000142871',
 'ENSG00000107201',
 'ENSG00000205327',
 'ENSG00000165376',
 'ENSG00000128564',
 'ENSG00000197561',
 'ENSG00000123307',
 'ENSG00000173621',
 'ENSG00000148123',
 'ENSG00000137747',
 'ENSG00000134817',
 'ENSG00000111181',
 'ENSG00000185614',
 'ENSG00000155158',
 'ENSG00000096968',
 'ENSG00000166866',
 'ENSG00000054356',
 'ENSG00000276043',

In [58]:
data.columns

Index(['ENSG00000000003', 'ENSG00000000005', 'ENSG00000000419',
       'ENSG00000000457', 'ENSG00000000460', 'ENSG00000000938',
       'ENSG00000000971', 'ENSG00000001036', 'ENSG00000001084',
       'ENSG00000001167',
       ...
       'ENSG00000289763', 'ENSG00000289764', 'ENSG00000289766',
       'ENSG00000289767', 'ENSG00000289768', 'ENSG00000289791',
       'ENSG00000289809', 'ENSG00000290146', 'ENSG00000290147',
       'ENSG00000290149'],
      dtype='object', length=20010)

In [54]:
data.columns

Index(['ENSG00000000003', 'ENSG00000000005', 'ENSG00000000419',
       'ENSG00000000457', 'ENSG00000000460', 'ENSG00000000938',
       'ENSG00000000971', 'ENSG00000001036', 'ENSG00000001084',
       'ENSG00000001167',
       ...
       'ENSG00000289763', 'ENSG00000289764', 'ENSG00000289766',
       'ENSG00000289767', 'ENSG00000289768', 'ENSG00000289791',
       'ENSG00000289809', 'ENSG00000290146', 'ENSG00000290147',
       'ENSG00000290149'],
      dtype='object', length=20010)