In [1]:
import pandas as pd

In [2]:
df_old = pd.read_csv("bulkformer_gene_info_old.csv")
df_new = pd.read_csv("bulkformer_gene_info.csv")
display(df_old)
df_new

,gene_symbol,ensg_id,gene_type,gene_length,ensp_id,protein_length
0,TSPAN6,ENSG00000000003,protein_coding,4530.0,ENSP00000362111,245.0
1,TNMD,ENSG00000000005,protein_coding,1476.0,ENSP00000362122,317.0
2,DPM1,ENSG00000000419,protein_coding,9276.0,ENSP00000360640,295.0
3,SCYL3,ENSG00000000457,protein_coding,6883.0,ENSP00000356744,742.0
4,C1orf112,ENSG00000000460,protein_coding,5970.0,ENSP00000286031,853.0
...,...,...,...,...,...,...
20006,ENSG00000289791,ENSG00000289791,protein_coding,1316.0,ENSP00000476965,288.0
20007,ENSG00000289809,ENSG00000289809,protein_coding,778.0,ENSP00000403093,163.0
20008,ENSG00000290146,ENSG00000290146,protein_coding,1292.0,ENSP00000480420,223.0
20009,ENSG00000290147,ENSG00000290147,protein_coding,2275.0,ENSP00000499539,201.0
20010,ENSG00000290149,ENSG00000290149,protein_coding,555.0,ENSP00000425858,122.0

,gene_symbol,ensg_id,gene_type,gene_length,ensp_id,Sequence,protein_length
0,TSPAN6,ENSG00000000003,protein_coding,4530,ENSP00000362111,MASPSRRLQTKPVITCFKSVLLIYTFIFWITGVILLAVGIWGKVSL...,245
1,TNMD,ENSG00000000005,protein_coding,1476,ENSP00000362122,MAKNPPENCEDCHILNAEAFKSKKICKSLKICGLVFGILALTLIVL...,317
2,DPM1,ENSG00000000419,protein_coding,9276,ENSP00000360640,MASLEVSRSPRRSRRELEVRSPRQNKYSVLLPTYNERENLPLIVWL...,295
3,SCYL3,ENSG00000000457,protein_coding,6883,ENSP00000356744,MGSENSALKSYTLREPPFTLPSGLAVYPAVLQDGKFASVFVYKREN...,742
4,C1orf112,ENSG00000000460,protein_coding,5970,ENSP00000286031,MFLPHMNHLTLEQTFFSQVLPKTVKLFDDMMYELTSQARGLSSQNL...,853
...,...,...,...,...,...,...,...
20005,ENSG00000289791,ENSG00000289791,protein_coding,1316,ENSP00000476965,MALQGISVVELSGLAPGPFCAMVLADFGARVVRVDRPGSRYDVSRL...,288
20006,ENSG00000289809,ENSG00000289809,protein_coding,778,ENSP00000403093,MGPFKHTVDDGLDVRKAAFECMYSLLESCLGQLDICEFLNHVEDGL...,163
20007,ENSG00000290146,ENSG00000290146,protein_coding,1292,ENSP00000480420,KMAAPSDGFKPRERSGGEQAQDWDALPPKRPRLGAGNKIGGRRLIV...,223
20008,ENSG00000290147,ENSG00000290147,protein_coding,2275,ENSP00000499539,MGNVMEGKSVEELSSTECHQWYKKFMTECPSGQLTLYEFRQFFGLK...,201
20009,ENSG00000290149,ENSG00000290149,protein_coding,555,ENSP00000425858,MFQIDQATKQCSKMTLTQPWDPLDIPQNSTFEDQYSIGGPQEQITV...,122

In [3]:
gs_old = set(df_old["gene_symbol"])
gs_old

{'ETV7',
 'DLX3',
 'TUBD1',
 'CHMP4B',
 'SLC38A10',
 'DRC7',
 'NR4A1',
 'HBD',
 'IAH1',
 'CLN5',
 'ENSG00000266953',
 'ATP5MC2',
 'GALE',
 'ZNF276',
 'ASIP',
 'ENSG00000272772',
 'OR7D2',
 'RNASE9',
 'ENSG00000273269',
 'ATP5PD',
 'NUP155',
 'HSD17B12',
 'ZNF623',
 'ENSG00000258653',
 'DNAH1',
 'TNP1',
 'ZC3H14',
 'ZNF660',
 'TSPAN16',
 'HSD11B2',
 'NCR3',
 'FAM240B',
 'OBP2A',
 'OR6C2',
 'DEFB116',
 'DIS3L2',
 'ACKR4',
 'BEX5',
 'SYNJ2BP-COX16',
 'CLSTN3',
 'ENSG00000289760',
 'SOX10',
 'PKD1',
 'ENSG00000258417',
 'ENSG00000288715',
 'RAP1A',
 'RPAP1',
 'OSBP',
 'ANAPC2',
 'CYCS',
 'RIC8B',
 'NOL4',
 'FMO5',
 'IGLL1',
 'PRDM8',
 'PPFIA3',
 'TMED10',
 'STAG2',
 'TNFRSF10B',
 'C10orf120',
 'KLK1',
 'CFAP161',
 'GNG13',
 'PYGO2',
 'CEACAM3',
 'ACSM4',
 'RUBCN',
 'AMPD1',
 'KLHDC8B',
 'CEP19',
 'H2AC4',
 'G6PC2',
 'OR1M1',
 'DENND6B',
 'SCRN1',
 'SPAM1',
 'NBPF4',
 'H3C2',
 'ADAMTS8',
 'CZIB',
 'MXI1',
 'ZNF35',
 'HCAR3',
 'GLP2R',
 'SST',
 'TMEM106C',
 'H4C9',
 'TATDN2',
 'MLANA',
 'LTBP3',
 'FCN3',
 'HLA-DQA1',
 'SRSF6',
 'PLA2G12B',
 'HHIPL1',
 'PABPN1',
 'HCK',
 'OR51G1',
 'ZBTB32',
 'H2BW2',
 'LBP',
 'SLC22A23',
 'FSIP1',
 'ZER1',
 'CLASP2',
 'RRN3',
 'MTIF3',
 'DHFR2',
 'IKBKG',
 'DGKZ',
 'SYCN',
 'TSPAN13',
 'SMIM27',
 'KLHL42',
 'SWT1',
 'BIRC7',
 'IL37',
 'MELTF',
 'TAX1BP1',
 'ART5',
 'DNASE2',
 'HDC',
 'ABCA13',
 'TLCD3A',
 'SLC39A5',
 'RPL31',
 'CTNNA1',
 'TAS2R40',
 'SETD3',
 'FADS2',
 'SEC24B',
 'ZNF577',
 'BYSL',
 'MTCP1',
 'FZD9',
 'BNIPL',
 'CST5',
 'C1QC',
 'ENSG00000206549',
 'TMEM213',
 'ADRA1A',
 'ATG4A',
 'SCAP',
 'ALDH18A1',
 'SMYD5',
 'L3MBTL1',
 'PPP4R3A',
 'CCND1',
 'TDGF1',
 'EPS15',
 'CHCHD4',
 'WDR61',
 'MACROD2',
 'FEZF2',
 'AOX1',
 'ZNF226',
 'C1QTNF3-AMACR',
 'TLCD5',
 'ACSM3',
 'CLEC18C',
 'HOXC8',
 'WDR31',
 'FAM90A12P',
 'ENSG00000254706',
 'CDK3',
 'COL25A1',
 'ZIM3',
 'HMGXB4',
 'TMCO5A',
 'FAM47E-STBD1',
 'XKR3',
 'PRR35',
 'YIPF2',
 'ARMT1',
 'NOL12',
 'IL20',
 'C2orf74',
 'NAGA',
 'FAM89B',
 'LELP1',
 'THAP5',
 'NFATC4',
 'RPH3AL',
 'IFNLR1',
 'KLC4',
 'ASS1',
 'CDHR3',
 'TANGO2',
 'ACR',
 'STARD8',
 'RALGAPB',
 'GAS2L1',
 'ENSG00000268655',
 'ANXA2',
 'KCNA2',
 'SMIM20',
 'AMELY',
 'ENSG00000269693',
 'LDOC1',
 'ANKDD1A',
 'HACD1',
 'GLYR1',
 'NCBP2L',
 'GPR6',
 'ENSG00000289281',
 'SAA4',
 'SCNN1B',
 'NECAB3',
 'PSMB5',
 'SLITRK3',
 'DSC1',
 'ITGA8',
 'RNF208',
 'IYD',
 'PCID2',
 'PROM2',
 'SAXO2',
 'FAM120C',
 'ABCA6',
 'TUG1',
 'MYBPC2',
 'AFF2',
 'RPS16',
 'BNIP2',
 'FAM90A20P',
 'BNIP5',
 'PDRG1',
 'SLCO1A2',
 'TXNL4A',
 'ATP8B4',
 'COL21A1',
 'SUN1',
 'NUDT8',
 'STAC2',
 'BASP1',
 'WASHC4',
 'EAF2',
 'GYS1',
 'ADA',
 'TNS1',
 'C11orf65',
 'IFNG',
 'HSD17B14',
 'KRI1',
 'TINAGL1',
 'VAV2',
 'TTC39B',
 'TRIP11',
 'ASPHD1',
 'HAL',
 'RABL2B',
 'BATF3',
 'FAM3D',
 'QRSL1',
 'CD33',
 'PATE2',
 'MAGEB2',
 'FAM216A',
 'PTBP2',
 'SETX',
 'CHD4',
 'AHCTF1',
 'DIABLO',
 'SPEF2',
 'LEF1',
 'RDH14',
 'NUDT10',
 'OGT',
 'AHR',
 'MED11',
 'FRRS1L',
 'ENSG00000282936',
 'RILPL2',
 'EPOR',
 'PCNP',
 'HSF4',
 'KAT8',
 'FAM167B',
 'RAB9A',
 'STMN4',
 'REV3L',
 'DAZAP1',
 'ZNF444',
 'PUS10',
 'ERBB3',
 'CUX1',
 'MAP7D1',
 'NFKB1',
 'MRPL41',
 'NBEAL2',
 'MOGAT2',
 'GGH',
 'ZNF879',
 'PLS1',
 'GASK1B',
 'SRXN1',
 'ZFX',
 'CAPZA1',
 'STAG3',
 'GCHFR',
 'PLXNB1',
 'PNMT',
 'ZC3HAV1L',
 'FAM90A3P',
 'TMEM68',
 'ATRX',
 'REC8',
 'SNX10',
 'MRM3',
 'CALY',
 'HS6ST1',
 'CDC42SE1',
 'GAS6',
 'ZNF487',
 'ORC3',
 'RUNDC1',
 'GIMAP6',
 'POLDIP2',
 'TMEM249',
 'C1orf54',
 'PRMT1',
 'METTL8',
 'ITM2B',
 'MAGEH1',
 'RSPH10B',
 'AMZ1',
 'SPEM3',
 'SEC63',
 'FAM120AOS',
 'DEFA1B',
 'GATA2',
 'CEP250',
 'ECSCR',
 'APOL4',
 'IQCF5',
 'MAGEL2',
 'NUMA1',
 'PLCE1',
 'GPAT2',
 'DENND2A',
 'WNT10A',
 'JPT1',
 'EGFL6',
 'CPNE5',
 'ENSG00000241962',
 'PHTF2',
 'ANTXR2',
 'TMEM102',
 'PCDH7',
 'ENSG00000284776',
 'OR8D2',
 'CCS',
 'SH3BGRL',
 'KLK3',
 'CYP7A1',
 'AMZ2',
 'CHPF2',
 'CDKN2AIPNL',
 'TDG',
 'RPL19',
 'OR2B11',
 'GARIN4',
 'ADGRF5',
 'AGTRAP',
 'WNT9A',
 'SLC12A1',
 'ZNF573',
 'PCMT1',
 'DDX58',
 'TMEM62',
 'CSMD3',
 'FOXD4L1',
 'PSMD6',
 'YAF2',
 'KRTAP4-16',
 'HNRNPCL2',
 'PLEKHS1',
 'CWH43',
 'L3MBTL3',
 'WFDC12',
 'ZNF467',
 'OVOL2',
 'VCAM1',
 'ROBO4',
 'COQ9',
 'OR13F1',
 'GSE1',
 'SSTR1',
 'ST8SIA1',
 'EDEM3',
 'PRR15L',
 'ATP6AP1',
 'SUCLA2',
 'RGS20',
 'PLK5',
 'VCP',
 'RTTN',
 'CENPN',
 'CYP2A6',
 'GLRX5',
 'SCGB2B2',
 'SMAD7',
 'KLHL32',
 'IDNK',
 'UCP3',
 'OR1N2',
 'FBXW12',
 'TMEM199',
 'EEF1AKMT2',
 'NOL4L',
 'ST8SIA2',
 'PRELID1',
 'FAM241A',
 'FER1L6',
 'DENND4C',
 'BMP2K',
 'ENSG00000273047',
 'PMS1',
 'SLITRK5',
 'ARPC4-TTLL3',
 'QTRT2',
 'COLEC12',
 'ATG9A',
 'PPP1R32',
 'ARMH2',
 'NTHL1',
 'TOR3A',
 'SLC15A1',
 'CNTNAP3C',
 'TPM2',
 'CLEC7A',
 'DUSP9',
 'TBC1D13',
 'SUN3',
 'NCF2',
 'NXNL2',
 'DUSP23',
 'NDUFS1',
 'ZNF267',
 'SPI1',
 'CENPE',
 'GTF2IRD2',
 'PLAC9',
 'OXER1',
 'ASL',
 'TRIP6',
 'PABIR2',
 'NAPA',
 'HDGFL2',
 'CSPG5',
 'AGO2',
 'CMTR2',
 'AFDN',
 'TTPA',
 'WARS1',
 'FZD4',
 'BNIP1',
 'AIFM3',
 'CYP4X1',
 'GRINA',
 'IFNGR2',
 'ZNF133',
 'CEP76',
 'FKBP15',
 'ART1',
 'ENSG00000259784',
 'MAGEB6',
 'GSS',
 'MLLT6',
 'SSTR2',
 'CWC22',
 'SNX17',
 'POTEJ',
 'TMEM60',
 'GAL3ST2',
 'TAF11L12',
 'ENSG00000286015',
 'SRBD1',
 'ALYREF',
 'NCAPH2',
 'COLCA2',
 'ZNF560',
 'DCP1B',
 'PACSIN3',
 'JUND',
 'OPN1MW2',
 'RTL4',
 'NFATC2',
 'CCDC186',
 'C19orf33',
 'NDUFA4L2',
 'OR4K15',
 'ORM2',
 'TTLL11',
 'PAQR5',
 'CFHR5',
 'ARF5',
 'TMEM104',
 'DEFB132',
 'ZNF547',
 'LRRFIP1',
 'PLCD1',
 'MOB3A',
 'ZNF407',
 'TMEM150A',
 'ELMOD1',
 'SPTBN5',
 'GPR34',
 'FBLN7',
 'GCG',
 'AMIGO1',
 'LRRTM2',
 'RRM2B',
 'ENSG00000271810',
 'FGD1',
 'SLC35B3',
 'NDST4',
 'SHC1',
 'GLDN',
 'CSMD1',
 'OR4F3',
 'FAM50A',
 'OCLN',
 'UBA3',
 'TBRG4',
 'CATSPERD',
 'CCDC28B',
 'PTDSS1',
 'CALCRL',
 'RBMX2',
 'KSR2',
 'INSYN2B',
 'PSMA2',
 'EIF3D',
 'CALHM5',
 'ENSG00000261832',
 'TCP11L2',
 'SIGIRR',
 'USP17L13',
 'ENSG00000285130',
 'KDM4B',
 'MUC2',
 'HSD11B1L',
 'DISP3',
 'UAP1L1',
 'FECH',
 'NAA80',
 'TMEM81',
 'SLC7A5',
 'APEH',
 'OR5K4',
 'ATP8B3',
 'PPP3CC',
 'STK10',
 'CA6',
 'POU2AF1',
 'WDR12',
 'CAMK2A',
 'VMO1',
 'ENSG00000272442',
 'P4HA3',
 'VPS4A',
 'SPDYE10',
 'PAMR1',
 'TMEM271',
 'CDH16',
 'CHMP2A',
 'JMY',
 'DLGAP2',
 'GRAMD2B',
 'KRTAP13-1',
 'TARDBP',
 'ALDOB',
 'TLE3',
 'PIK3R5',
 'IL6ST',
 'RNF215',
 'RASSF8',
 'FAR1',
 'OR10G3',
 'ATE1',
 'EIF4E2',
 'CHRM2',
 'CTAGE15',
 'PLPP4',
 'ABCD2',
 'CCDC30',
 'NPS',
 'MTCH1',
 'MYO6',
 'MAT2B',
 'HES6',
 'TNFAIP3',
 'PAG1',
 'SIGLEC10',
 'ZNF124',
 'OPTN',
 'ZNF878',
 'SMIM1',
 'IRGQ',
 'FAM131C',
 'CXCR4',
 'KLF1',
 'KLF4',
 'ITGA4',
 'BIK',
 'OCEL1',
 'TM9SF2',
 'TPM4',
 'C16orf90',
 'CTH',
 'CCL15',
 'KBTBD6',
 'CSTA',
 'RNF222',
 'RRM2',
 'PAQR3',
 'ENSG00000266302',
 'UBQLN1',
 'NTN1',
 'PARP16',
 'LIN52',
 'H2AZ1',
 'OTULINL',
 'HSPA8',
 'EMX2',
 'ST6GALNAC5',
 'UGT1A8',
 'DNAAF10',
 'TP53TG3B',
 'ADAMTS19',
 'TCF7L2',
 'PCDHB13',
 'KCNE5',
 'PFDN1',
 'PGR',
 'SOX15',
 'BTG2',
 'BAG5',
 'NPIPB5',
 'NMI',
 'CDHR1',
 'CAMKK2',
 'SYAP1',
 'DMTN',
 'ACTR3',
 'ST8SIA6',
 'PPBP',
 'KITLG',
 'ZNF609',
 'MYO15A',
 'NFE2L2',
 'TMEM144',
 'TMBIM6',
 'SMTNL1',
 'MYH7',
 'GLRA2',
 'MACIR',
 'ENSG00000269242',
 'ZNF512B',
 'VAT1',
 'PDCD6',
 'ZSCAN18',
 'EXTL3',
 'MBD3L5',
 'TMEM236',
 'FBXL5',
 'MEGF10',
 'TBC1D31',
 'TARM1',
 'TBX1',
 'RPS15',
 'VPS33A',
 'NKX2-3',
 'FLG2',
 'IRX6',
 'MPPED2',
 'LRWD1',
 'LAD1',
 'ZNF296',
 'KRT79',
 'NDUFS4',
 'H2AC16',
 'EGR4',
 'IGSF9',
 'HESX1',
 'ENSG00000273171',
 'NMD3',
 'EGR2',
 'ZCCHC7',
 'SGIP1',
 'NEUROG1',
 'MICALL2',
 'ENSG00000285238',
 'NOP16',
 'RAB42',
 'ENSG00000260836',
 'ZDHHC24',
 'KIF3B',
 'HGF',
 'OR9A1P',
 'CELSR1',
 'DCC',
 'IL22',
 'STAMBP',
 'TFF3',
 'ZFP69',
 'GLRX',
 'ZFP69B',
 'PDE7B',
 'CASP7',
 'SORL1',
 'ZNF727',
 'OR2W1',
 'FBLL1',
 'ENSG00000272741',
 'SPDYE5',
 'UBE2T',
 'SCYGR10',
 'TRAPPC10',
 'PIGF',
 'TRAPPC3L',
 'CHMP7',
 'SFRP2',
 'LMNTD1',
 'NDUFB5',
 'KRTAP19-2',
 'GDPD3',
 'MAP1LC3C',
 'PEPD',
 'ENSG00000258864',
 'MPP1',
 'KRTAP2-1',
 'IL1RAPL1',
 'MAPK13',
 'GGTLC3',
 'POTEF',
 'PLAC8',
 'CRNKL1',
 'ZNF90',
 'CRY1',
 'SPACA5',
 'TMED1',
 'KRT18',
 'C1orf109',
 'RFX8',
 'USP4',
 'GLYATL2',
 'CD96',
 'GJA1',
 'GLIPR1L1',
 'DEFB128',
 'NLRP1',
 'MCFD2',
 'ECM2',
 'PIK3IP1',
 'WFDC5',
 'SULT1C3',
 'TP53TG3E',
 'DACT3',
 'KRTAP19-3',
 'UCN',
 'ACTR8',
 'AP1M1',
 'PCDHA13',
 'KLHL12',
 'CCDC122',
 'NCOA1',
 'PTH2R',
 'DLL1',
 'ZFP41',
 'ADAM9',
 'LRP10',
 'UTP4',
 'RNASEK',
 'PRAG1',
 'CDO1',
 'ENSG00000277639',
 'INIP',
 'MBD3L4',
 'DMRTB1',
 'IFIT1',
 'UFM1',
 'TEX13B',
 'MAP1LC3A',
 'ECRG4',
 'ADORA3',
 'SMG8',
 'CENPC',
 'SMARCD1',
 'PLEKHD1',
 'OR4L1',
 'HMGB1',
 'ICE2',
 'LOXL3',
 'PSAT1',
 'TMED5',
 'PEX5',
 'PPP1R3G',
 'TRMT10C',
 'KIF5A',
 'METAP1D',
 'GINM1',
 'BAX',
 'ENSG00000256206',
 'CLDN22',
 'HLA-A',
 'LSM8',
 'CYP2C9',
 'TVP23A',
 'RGS3',
 'FAM193B',
 'LYPD2',
 'PABPC4',
 'H2AW',
 'ERGIC2',
 'ZNF205',
 'CSN3',
 'AFAP1',
 'RUSF1',
 'POU2F3',
 'L1CAM',
 'ADAMTS17',
 'NEK5',
 'SLCO2B1',
 'KRTAP9-6',
 'HEATR1',
 'PIK3CD',
 'NPRL3',
 'ZNF682',
 'SCGB1D2',
 'UTP15',
 'C8orf58',
 'CNR2',
 'MRPL23',
 'ISLR',
 'SMIM34',
 'MTUS2',
 'CCNL1',
 'OR52B6',
 'OR11G2',
 'UGT2B11',
 'DTWD2',
 'PDHA1',
 'KRTAP9-1',
 'ZNF446',
 'GPD2',
 'C9orf153',
 'HDAC11',
 'DESI2',
 'RAB22A',
 'GOLGA6L1',
 'PAK2',
 'CLPB',
 'NAV2',
 'PEX11B',
 'TLN1',
 'AGFG1',
 'NOP9',
 'SPATA32',
 'KRT6B',
 'GZMA',
 'MOV10',
 'UGT3A1',
 'IHO1',
 'KCNK1',
 'FOXRED1',
 'GGT6',
 'TEX19',
 'TBL3',
 'SPEN',
 'A2ML1',
 'RP9',
 'TMEM106B',
 'SAMD12',
 'GSK3A',
 'DMRT2',
 'ENGASE',
 'RESF1',
 'CST4',
 'ATP6V1B1',
 'ALG11',
 'DEGS2',
 'BCL2L11',
 'ABCD3',
 'SCOC',
 'CCNB1',
 'HNRNPA3',
 'HMGB4',
 'OR5B3',
 'ADM5',
 'PPP4R3C',
 'SELENOP',
 'MIB1',
 'IMP4',
 'AP5S1',
 'ENSG00000187186',
 'TAF11L6',
 'GAN',
 'APC',
 'OR2F2',
 'SLC47A2',
 'RIMBP3',
 'RIPK3',
 'POLR3K',
 'EIF5A',
 'ENSG00000288626',
 'LYST',
 'SRL',
 'PDP1',
 'KDELR2',
 'TCEAL2',
 'DNASE1L1',
 'PCGF1',
 'GOLGA8Q',
 'ITGAV',
 'STK16',
 'PDE6B',
 'PTPA',
 'SNRPD1',
 'HSFY2',
 'TBX4',
 'DMRTA2',
 'MEF2D',
 'KBTBD13',
 'ENSG00000264668',
 'TP53I13',
 'BAAT',
 'RNF125',
 'BEND6',
 'KLHL7',
 'ENSG00000273748',
 'RLN3',
 'STARD10',
 'ZNF419',
 'RORA',
 'GDF10',
 'TMEM275',
 'ENSG00000173867',
 'SPATA16',
 'POLR2C',
 'SIGMAR1',
 'ITIH2',
 'ZNF707',
 'CDC25C',
 'CFAP298',
 'NHLH1',
 'PPAN-P2RY11',
 'ADAMTS7',
 'ATP6V0E1',
 'CCDC183',
 'OR4D2',
 'NCCRP1',
 'UBE2V1',
 'PCYOX1',
 'FAM47B',
 'ENSG00000283189',
 'CKS2',
 'NR5A1',
 'DNPH1',
 'TRIM64C',
 'TSPAN18',
 'GALNT4',
 'NFAT5',
 'SMIM14',
 'ELP5',
 'TCFL5',
 'CCDC96',
 'ARMC2',
 'ZGRF1',
 'CT47A3',
 'C5AR1',
 'ENSG00000271949',
 'RIPK4',
 'SLC25A53',
 'AGPAT4',
 'CFB',
 'VSTM2L',
 'NUTM2E',
 'FADD',
 'IFNA6',
 'OR2A2',
 'GFM1',
 'MYO18B',
 'SLC25A42',
 'USP17L23',
 'CASP6',
 'TTC34',
 'STAB2',
 'PYCR3',
 'SEMA6B',
 'TSPY10',
 'PEBP1',
 'ANKRD40CL',
 'NTRK3',
 'ZSCAN22',
 'SPATA31A6',
 'PCDH10',
 'OSBPL9',
 'NDUFAF1',
 ...}

In [4]:
genes_old = set(df_old["gene_symbol"])
genes_new = set(df_new["gene_symbol"])
genes_old.difference(genes_new)

{'VIKEADRGDSGTYDLVLENKCGKKAVYIKVRVIGSPNSPEGPLEYDDIQVRSVRVSWRPPADDGGADILGYILERREVPKAAWYTIDSRVRGTSLVVKGLKENVEYHFRVSAENQFGISKPLKSEEPVTPKTPLNPPEPPSNPPEVLDVTKSSVSLSWSRPKDDGGSRVTGYYIERKETSTDKWVRHNKTQITTTMYTVTGLVPDAEYQFRIIAQNDVGLSETSPASEPVVCKDPFDKPSQPGELEILSISKDSVTLQWEKPECDGGKEILGYWVEYRQSGDSAWKKSNKERIKDKQFTIGGLLEATEYEFRVFAENETGLSRPRRTAMSIKTKLTSGEAPGIRKEMKDVTTKLGEAAQLSCQIVGRPLPDIKWYRFGKELIQSRKYKMSSDGRTHTLTVMTEEQEDEGVYTCIATNEVGEVETSSKLLLQATPQFHPGYPLKEKYYGAVGSTLRLHVMYIGRPVPAMTWFHGQKLLQNSENITIENTEHYTHLVMKNVQRKTHAGKYKVQLSNVFGTVDAILDVEIQDKPDKPTGPIVIEALLKNSAVISWKPPADDGGSWITNYVVEKCEAKEGAEWQLVSSAISVTTCRIVNLTENAGYYFRVSAQNTFGISDPLEVSSVVIIKSPFEKPGAPGKPTITAVTKDSCVVAWKPPASDGGAKIRNYYLEKREKKQNKWISVTTEEIRETVFSVKNLIEGLEYEFRVKCENLGGESEWSEISEPITPKSDVPIQAPHFKEELRNLNVRYQSNATLVCKVTGHPKPIVKWYRQGKEIIADGLKYRIQEFKGGYHQLIIASVTDDDATVYQVRATNQGGSVSGTASLEVEVPAKIHLPKTLEGMGAVHALRGEVVSIKIPFSGKPDPVITWQKGQDLIDNNGHYQVIVTRSFTSLVFPNGVERKDAGFYVVCAKNRFGIDQKTVELDVADVPDPPRGVKVSDVSRDSVNLTWTEPASDGGSKITNYIVEKCATTAERWLRVGQARETRYTVINLFGKTSYQFRVIAENKFGLSKPSEPSEPTITKEDKTRAMNYDEEVDETREVSMTKASHSSTKELYEKYMIAEDLGRGEFGIVHRCVETSSKKTYMAKFVKVKGTDQVLVKKEISILNIARHRNILHLHESFESMEELVMIFEFISGLDIFERINTSAFELNEREIVSYVHQVCEALQFLHSHNIGHFDIRPENIIYQTRRSSTIKIIEFGQARQLKPGDNFRLLFTAPEYYAPEVHQHDVVSTATDMWSLGTLVYVLLSGINPFLAETNQQIIENIMNAEYTFDEEAFKEISIEAMDFVDRLLVKERKSRMTASEALQHPWLKQKIERVSTKVIRTLKHRRYYHTLIKKDLNMVVSAARISCGGAIRSQKGVSVAKVKVASIEIGPVSGQIMHAVGEEGGHVKYVCKIENYDQSTQVTWYFGVRQLENSEKYEITYEDGVAILYVKDITKLDDGTYRCKVVNDYGEDSSYAELFVKGVREVYDYYCRRTMKKIKRRTDTMRLLERPPEFTLPLYNKTAYVGENVRFGVTITVHPEPHVTWYKSGQKIKPGDNDKKYTFESDKGLYQLTINSVTTDDDAEYTVVARNKYGEDSCKAKLTVTLHPPPTDSTLRPMFKRLLANAECQEGQSVCFEIRVSGIPPPTLKWEKDGQPLSLGPNIEIIHEGLDYYALHIRDTLPEDTGYYRVTATNTAGSTSCQAHLQVERLRYKKQEFKSKEEHERHVQKQIDKTLRMAEILSGTESVPLTQVAKEALREAAVLYKPAVSTKTVKGEFRLEIEEKKEERKLRMPYDVPEPRKYKQTTIEEDQRIKQFVPMSDMKWYKKIRDQYEMPGKLDRVVQKRPKRIRLSRWEQFYVMPLPRITDQYRPKWRIPKLSQDDLEIVRPARRRTPSPDYDFYYRPRRRSLGDISDEELLLPIDDYLAMKRTEEERLRLEEELELGFSASPPSRSPPHFELSSLRYSSPQAHVKVEETRKDFRYSTYHIPTKAEASTSYAELRERHAQAAYRQPKQRQRIMAEREDEELLRPVTTTQHLSEYKSELDFMSKEEKSRKKSRRQREVTEITEIEEEYEISKHAQRESSSSASRLLRRRRSLSPTYIELMRPVSELIRSRPQPAEEYEDDTERRSPTPERTRPRSPSPVSSERSLSRFERSARFDIFSRYESMKAALKTQKTSERKYEVLSQQPFTLDHAPRITLRMRSHRVPCGQNTRFILNVQSKPTAEVKWYHNGVELQESSKIHYTNTSGVLTLEILDCHTDDSGTYRAVCTNYKGEASDYATLDVTGGDYTTYASQRRDEEVPRSVFPELTRTEAYAVSSFKKTSEMEASSSVREVKSQMTETRESLSSYEHSASAEMKSAALEEKSLEEKSTTRKIKTTLAARILTKPRSMTVYEGESARFSCDTDGEPVPTVTWLRKGQVLSTSARHQVTTTKYKSTFEISSVQASDEGNYSVVVENSEGKQEAEFTLTIQKARVTEKAVTSPPRVKSPEPRVKSPEAVKSPKRVKSPEPSHPKAVSPTETKPTPTEKVQHLPVSAPPKITQFLKAEASKEIAKLTCVVESSVLRAKEVTWYKDGKKLKENGHFQFHYSADGTYELKINNLTESDQGEYVCEISGEGGTSKTNLQFMGQAFKSIHEKVSKISETKKSDQKTTESTVTRKTEPKAPEPISSKPVIVTGLQDTTVSSDSVAKFAVKATGEPRPTAIWTKDGKAITQGGKYKLSEDKGGFFLEIHKTDTSDSGLYTCTVKNSAGSVSSSCKLTIKAIKDTEAQKVSTQKTSEITPQKKAVVQEEISQKALRSEEIKMSEAKSQEKLALKEEASKVLISEEVKKSAATSLEKSIVHEEITKTSQASEEVRTHAEIKAFSTQMSINEGQRLVLKANIAGATDVKWVLNGVELTNSEEYRYGVSGSDQTLTIKQASHRDEGILTCISKTKEGIVKCQYDLTLSKELSDAPAFISQPRSQNINEGQNVLFTCEISGEPSPEIEWFKNNLPISISSNVSISRSRNVYSLEIRNASVSDSGKYTIKAKNFRGQCSATASLMVLPLVEEPSREVVLRTSGDTSLQGSFSSQSVQMSASKQEASFSSFSSSSASSMTEMKFASMSAQSMSSMQESFVEMSSSSFMGISNMTQLESSTSKMLKAGIRGIPPKIEALPSDISIDEGKVLTVACAFTGEPTPEVTWSCGGRKIHSQEQGRFHIENTDDLTTLIIMDVQKQDGGLYTLSLGNEFGSDSATVNIHIRSI'}

In [5]:
len(genes_new.intersection(genes_old))

20007

In [6]:
genes_new.difference(genes_old)

set()

In [7]:
len(genes_old.difference(genes_new))

1

In [8]:
len(genes_old.symmetric_difference(genes_new))

1

In [9]:
(df_old["gene_symbol"] == 'VIKEADRGDSGTYDLVLENKCGKKAVYIKVRVIGSPNSPEGPLEYDDIQVRSVRVSWRPPADDGGADILGYILERREVPKAAWYTIDSRVRGTSLVVKGLKENVEYHFRVSAENQFGISKPLKSEEPVTPKTPLNPPEPPSNPPEVLDVTKSSVSLSWSRPKDDGGSRVTGYYIERKETSTDKWVRHNKTQITTTMYTVTGLVPDAEYQFRIIAQNDVGLSETSPASEPVVCKDPFDKPSQPGELEILSISKDSVTLQWEKPECDGGKEILGYWVEYRQSGDSAWKKSNKERIKDKQFTIGGLLEATEYEFRVFAENETGLSRPRRTAMSIKTKLTSGEAPGIRKEMKDVTTKLGEAAQLSCQIVGRPLPDIKWYRFGKELIQSRKYKMSSDGRTHTLTVMTEEQEDEGVYTCIATNEVGEVETSSKLLLQATPQFHPGYPLKEKYYGAVGSTLRLHVMYIGRPVPAMTWFHGQKLLQNSENITIENTEHYTHLVMKNVQRKTHAGKYKVQLSNVFGTVDAILDVEIQDKPDKPTGPIVIEALLKNSAVISWKPPADDGGSWITNYVVEKCEAKEGAEWQLVSSAISVTTCRIVNLTENAGYYFRVSAQNTFGISDPLEVSSVVIIKSPFEKPGAPGKPTITAVTKDSCVVAWKPPASDGGAKIRNYYLEKREKKQNKWISVTTEEIRETVFSVKNLIEGLEYEFRVKCENLGGESEWSEISEPITPKSDVPIQAPHFKEELRNLNVRYQSNATLVCKVTGHPKPIVKWYRQGKEIIADGLKYRIQEFKGGYHQLIIASVTDDDATVYQVRATNQGGSVSGTASLEVEVPAKIHLPKTLEGMGAVHALRGEVVSIKIPFSGKPDPVITWQKGQDLIDNNGHYQVIVTRSFTSLVFPNGVERKDAGFYVVCAKNRFGIDQKTVELDVADVPDPPRGVKVSDVSRDSVNLTWTEPASDGGSKITNYIVEKCATTAERWLRVGQARETRYTVINLFGKTSYQFRVIAENKFGLSKPSEPSEPTITKEDKTRAMNYDEEVDETREVSMTKASHSSTKELYEKYMIAEDLGRGEFGIVHRCVETSSKKTYMAKFVKVKGTDQVLVKKEISILNIARHRNILHLHESFESMEELVMIFEFISGLDIFERINTSAFELNEREIVSYVHQVCEALQFLHSHNIGHFDIRPENIIYQTRRSSTIKIIEFGQARQLKPGDNFRLLFTAPEYYAPEVHQHDVVSTATDMWSLGTLVYVLLSGINPFLAETNQQIIENIMNAEYTFDEEAFKEISIEAMDFVDRLLVKERKSRMTASEALQHPWLKQKIERVSTKVIRTLKHRRYYHTLIKKDLNMVVSAARISCGGAIRSQKGVSVAKVKVASIEIGPVSGQIMHAVGEEGGHVKYVCKIENYDQSTQVTWYFGVRQLENSEKYEITYEDGVAILYVKDITKLDDGTYRCKVVNDYGEDSSYAELFVKGVREVYDYYCRRTMKKIKRRTDTMRLLERPPEFTLPLYNKTAYVGENVRFGVTITVHPEPHVTWYKSGQKIKPGDNDKKYTFESDKGLYQLTINSVTTDDDAEYTVVARNKYGEDSCKAKLTVTLHPPPTDSTLRPMFKRLLANAECQEGQSVCFEIRVSGIPPPTLKWEKDGQPLSLGPNIEIIHEGLDYYALHIRDTLPEDTGYYRVTATNTAGSTSCQAHLQVERLRYKKQEFKSKEEHERHVQKQIDKTLRMAEILSGTESVPLTQVAKEALREAAVLYKPAVSTKTVKGEFRLEIEEKKEERKLRMPYDVPEPRKYKQTTIEEDQRIKQFVPMSDMKWYKKIRDQYEMPGKLDRVVQKRPKRIRLSRWEQFYVMPLPRITDQYRPKWRIPKLSQDDLEIVRPARRRTPSPDYDFYYRPRRRSLGDISDEELLLPIDDYLAMKRTEEERLRLEEELELGFSASPPSRSPPHFELSSLRYSSPQAHVKVEETRKDFRYSTYHIPTKAEASTSYAELRERHAQAAYRQPKQRQRIMAEREDEELLRPVTTTQHLSEYKSELDFMSKEEKSRKKSRRQREVTEITEIEEEYEISKHAQRESSSSASRLLRRRRSLSPTYIELMRPVSELIRSRPQPAEEYEDDTERRSPTPERTRPRSPSPVSSERSLSRFERSARFDIFSRYESMKAALKTQKTSERKYEVLSQQPFTLDHAPRITLRMRSHRVPCGQNTRFILNVQSKPTAEVKWYHNGVELQESSKIHYTNTSGVLTLEILDCHTDDSGTYRAVCTNYKGEASDYATLDVTGGDYTTYASQRRDEEVPRSVFPELTRTEAYAVSSFKKTSEMEASSSVREVKSQMTETRESLSSYEHSASAEMKSAALEEKSLEEKSTTRKIKTTLAARILTKPRSMTVYEGESARFSCDTDGEPVPTVTWLRKGQVLSTSARHQVTTTKYKSTFEISSVQASDEGNYSVVVENSEGKQEAEFTLTIQKARVTEKAVTSPPRVKSPEPRVKSPEAVKSPKRVKSPEPSHPKAVSPTETKPTPTEKVQHLPVSAPPKITQFLKAEASKEIAKLTCVVESSVLRAKEVTWYKDGKKLKENGHFQFHYSADGTYELKINNLTESDQGEYVCEISGEGGTSKTNLQFMGQAFKSIHEKVSKISETKKSDQKTTESTVTRKTEPKAPEPISSKPVIVTGLQDTTVSSDSVAKFAVKATGEPRPTAIWTKDGKAITQGGKYKLSEDKGGFFLEIHKTDTSDSGLYTCTVKNSAGSVSSSCKLTIKAIKDTEAQKVSTQKTSEITPQKKAVVQEEISQKALRSEEIKMSEAKSQEKLALKEEASKVLISEEVKKSAATSLEKSIVHEEITKTSQASEEVRTHAEIKAFSTQMSINEGQRLVLKANIAGATDVKWVLNGVELTNSEEYRYGVSGSDQTLTIKQASHRDEGILTCISKTKEGIVKCQYDLTLSKELSDAPAFISQPRSQNINEGQNVLFTCEISGEPSPEIEWFKNNLPISISSNVSISRSRNVYSLEIRNASVSDSGKYTIKAKNFRGQCSATASLMVLPLVEEPSREVVLRTSGDTSLQGSFSSQSVQMSASKQEASFSSFSSSSASSMTEMKFASMSAQSMSSMQESFVEMSSSSFMGISNMTQLESSTSKMLKAGIRGIPPKIEALPSDISIDEGKVLTVACAFTGEPTPEVTWSCGGRKIHSQEQGRFHIENTDDLTTLIIMDVQKQDGGLYTLSLGNEFGSDSATVNIHIRSI').argmax()

np.int64(9736)

In [10]:
df_old.iloc[9736]

gene_symbol       VIKEADRGDSGTYDLVLENKCGKKAVYIKVRVIGSPNSPEGPLEYD...
ensg_id                                                       35991
gene_type                                                       NaN
gene_length                                                     NaN
ensp_id                                                         NaN
protein_length                                                  NaN
Name: 9736, dtype: object

In [11]:
# something not adding up here, 20,011 rows in old, 20,010 in new.
# but only 20,007 in common?
# 3 duplicate genes, now adds up, perhaps gene symbol not unique and ensembl id not shared here
df_old["gene_symbol"].isna().any()

np.False_

In [12]:
df_old["gene_symbol"].value_counts(ascending=False)

gene_symbol
POLR2J3    2
PINX1      2
TBCE       2
MARCHF3    1
CBY2       1
          ..
MKRN1      1
ADCK2      1
GIMAP4     1
GIMAP6     1
LRRIQ1     1
Name: count, Length: 20008, dtype: int64

In [13]:
df_new["gene_symbol"].value_counts(ascending=False)

gene_symbol
POLR2J3    2
PINX1      2
TBCE       2
SWSAP1     1
TENT5D     1
          ..
MKRN1      1
ADCK2      1
GIMAP4     1
GIMAP6     1
LRRIQ1     1
Name: count, Length: 20007, dtype: int64

In [14]:
# indeed, duplicate genes
# -> are a lot of the genes also duplicated with the unlabeled set? 
dup_genes = [
    "POLR2J3",
    "PINX1",
    "TBCE"
]
df_new[df_new.gene_symbol.isin(dup_genes)]

,gene_symbol,ensg_id,gene_type,gene_length,ensp_id,Sequence,protein_length
12089,POLR2J3,ENSG00000168255,protein_coding,3190,ENSP00000421085,MNAPPAFESFLLFEGEKITINKDTKVPNACLFTINKEDHTLGNIIK...,274
18626,PINX1,ENSG00000254093,protein_coding,2804,ENSP00000428728,MSMLAERECRKRRPDPGRRKQKWAVDPQNTAWSNDDSKFGQRMLEK...,338
18847,PINX1,ENSG00000258724,protein_coding,1753,ENSP00000451145,MSMLAERRRKQKWAVDPQNTAWSNDDSKFGQRMLEKMGWSKGKGLG...,440
19723,TBCE,ENSG00000284770,protein_coding,12444,ENSP00000439170,MSDTLTADVIGRRVEVNGEHATVRFAGVVPPVAGPWLGVEWDNPER...,578
19754,TBCE,ENSG00000285053,protein_coding,5184,ENSP00000494575,MSDTLTADVIGRRVEVNGEHATVRFAGVVPPVAGPWLGVEWDNPER...,527
19776,POLR2J3,ENSG00000285437,protein_coding,6795,ENSP00000477228,MNAPPAFESFLLFEGEKITINKDTKVPNACLFTINKEDHTLGNIIK...,115

In [15]:
df_unlabelled = pd.read_csv("~/UCLThesis/data/BIOAID2_tpm_PC0.001_log2.csv")
df_unlabelled

,ensembl_gene_id,BIOAIDUR7635328,BIOAIDUR7635329,BIOAIDUR7635330,BIOAIDUR7635331,BIOAIDUR7635333,BIOAIDUR7635334,BIOAIDUR7635335,BIOAIDUR7635336,BIOAIDUR7635337,...,BIOAIDUR7638377,BIOAIDUR7638378,BIOAIDUR7638379,BIOAIDUR7638380,BIOAIDUR7638381,BIOAIDUR7638382,BIOAIDUR7638383,BIOAIDUR7638384,BIOAIDUR7638385,BIOAIDUR7638386
0,ENSG00000000003,-3.596095,-5.949696,-4.505073,-2.106934,-4.988783,-1.850323,-2.469483,-3.062416,-2.984260,...,-2.652157,-3.238749,-3.171749,-9.965784,-3.523180,-2.818299,-5.817195,-3.708418,-3.580042,-3.291908
1,ENSG00000000005,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,...,-9.965784,-9.965784,-9.965784,-9.965784,-4.210352,-9.965784,-9.965784,-9.965784,-4.320006,-9.965784
2,ENSG00000000419,5.700050,5.477522,5.299801,5.930045,5.191968,5.708400,5.548016,5.974900,5.875727,...,5.325510,5.303819,5.264936,5.611836,5.526845,4.085649,5.456692,5.285920,5.179491,5.506388
3,ENSG00000000457,2.922647,2.584519,2.761906,3.491873,2.242854,3.745218,4.066507,2.963874,3.117342,...,2.562418,2.685328,2.343431,3.187963,3.161634,1.670864,3.832969,3.132869,2.288755,3.502589
4,ENSG00000000460,0.637525,-0.381749,0.408494,2.409785,-0.538535,0.346656,1.331709,0.281370,0.795487,...,0.152590,-0.561340,-0.328361,1.529748,0.374070,-1.181407,0.225913,-0.272933,-0.040647,0.621578
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41122,ENSG00000310560,5.065582,4.884832,5.460196,6.286006,5.011928,5.134283,5.218658,6.100866,4.753330,...,4.858180,5.034496,4.902136,5.814492,5.352256,4.418302,5.193814,4.834661,5.776209,5.629923
41123,ENSG00000310561,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,...,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784
41124,ENSG00000310562,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,...,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784
41125,ENSG00000310564,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,...,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784,-9.965784
41126,ENSG00000310576,4.700174,4.714325,5.031022,5.479512,4.645988,5.279765,5.223697,5.110488,4.154583,...,5.152926,4.922024,4.949370,5.292347,5.406522,4.181274,4.584931,5.048290,5.099916,5.020117

In [20]:
gene_id_unlabelled = set(df_unlabelled["ensembl_gene_id"])

# almost all the genes are there
len(gene_id_unlabelled.intersection(set(df_new["ensg_id"])))
# set(df_new["gene_symbol"]).difference(gene_id_unlabelled)

20006

In [21]:
# Try labelled dataset
df_labelled = pd.read_csv("~/UCLThesis/data/BIOAID_tpm_PC0.001_log2.csv")
gene_id_labelled = set(df_labelled["ensembl_gene_id"])

# all genes there
# would be good to double check/rerun everything with ensembl_gene_id instead
len(gene_id_labelled.intersection(df_new["ensg_id"]))

20010